table dim_setor_atendimento
	lineageTag: 03f81f84-e28c-44ea-b47e-519d71275ecb

	column cd_setor_atendimento
		dataType: int64
		formatString: 0
		lineageTag: 4cfc8888-2ffb-4cdd-b5af-8a4ccfa00927
		summarizeBy: none
		sourceColumn: Setor_Atendimento___Codigo

		annotation SummarizationSetBy = Automatic

	column ds_setor_atendimento
		dataType: string
		lineageTag: 84e9dc3e-554b-4d9f-a2b6-5752dcc75dbd
		summarizeBy: none
		sourceColumn: Setor_Atendimento___Descricao

		annotation SummarizationSetBy = Automatic

	column Centro_Custo___Codigo
		dataType: int64
		formatString: 0
		lineageTag: 5e5713be-bfb9-4c6b-836b-55e76caf1840
		summarizeBy: sum
		sourceColumn: Centro_Custo___Codigo

		annotation SummarizationSetBy = Automatic

	column cd_classif_setor
		dataType: string
		lineageTag: 1889fdff-9e7c-4e0f-a2b3-0e179e853697
		summarizeBy: none
		sourceColumn: Classificacao_Setor___Codigo_Descricao

		annotation SummarizationSetBy = Automatic

	column ds_classif_setor
		dataType: string
		lineageTag: 04671835-2c07-4045-a570-3c02fadc181e
		summarizeBy: none
		sourceColumn: Classificacao_Setor___Descricao

		annotation SummarizationSetBy = Automatic

	column Setor_Atendimento___Codigo_Descricao
		dataType: string
		lineageTag: 07e9170d-45b0-485f-9189-e25e95fc0a47
		summarizeBy: none
		sourceColumn: Setor_Atendimento___Codigo_Descricao

		annotation SummarizationSetBy = Automatic

	partition dim_setor_atendimento = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\luanp\Downloads\dim_setor_atendimento_202603191235.csv"),[Delimiter=",", Columns=6, Encoding=65001]),
				    #"Usar a Primeira Linha como Cabeçalho" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Alterar Tipo" = Table.TransformColumnTypes(#"Usar a Primeira Linha como Cabeçalho",{{"Setor_Atendimento___Codigo", Int64.Type}, {"Setor_Atendimento___Descricao", type text}, {"Centro_Custo___Codigo", Int64.Type}, {"Classificacao_Setor___Codigo_Descricao", type text}, {"Classificacao_Setor___Descricao", type text}, {"Setor_Atendimento___Codigo_Descricao", type text}})
				in
				    #"Alterar Tipo"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

