table 'Indicador 06'
	lineageTag: 2edcc155-90b8-400d-8c32-b97850d5d20f

	column NR_ATENDIMENTO
		dataType: int64
		formatString: 0
		lineageTag: e31532fe-01bd-488e-b8fc-e060ea519b2c
		summarizeBy: none
		sourceColumn: NR_ATENDIMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_ESTABELECIMENTO
		dataType: string
		lineageTag: f34c4121-5554-41f8-bd49-04f88ac36673
		summarizeBy: none
		sourceColumn: CD_ESTABELECIMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_PESSOA_FISICA
		dataType: string
		lineageTag: cb61c1d9-55e7-43fa-b278-e535b36abf77
		summarizeBy: none
		sourceColumn: CD_PESSOA_FISICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_SETOR_ATENDIMENTO
		dataType: int64
		formatString: 0
		lineageTag: 428a12d3-ad95-4770-88b1-09017d1097b6
		summarizeBy: none
		sourceColumn: CD_SETOR_ATENDIMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_CID
		dataType: string
		lineageTag: 3aecdeed-cf3d-4fc8-8d9b-a6c015bc67f5
		summarizeBy: none
		sourceColumn: CD_CID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_ENTRADA_UNIDADE
		dataType: dateTime
		formatString: General Date
		lineageTag: 4dc86b7e-38db-44bf-9d92-97b2f9e28138
		summarizeBy: none
		sourceColumn: DT_ENTRADA_UNIDADE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE
		dataType: string
		lineageTag: ea3f6b7c-325f-476f-b4f5-ccde479dbb5f
		summarizeBy: none
		sourceColumn: CD_UNIDADE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_BASICA
		dataType: string
		lineageTag: 5a1a77b0-9626-4299-96a5-b93386df0561
		summarizeBy: none
		sourceColumn: CD_UNIDADE_BASICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_UNIDADE_COMPL
		dataType: string
		lineageTag: 8f2233e4-ed5b-412c-bf34-377ebd8c459a
		summarizeBy: none
		sourceColumn: CD_UNIDADE_COMPL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_ENTRADA
		dataType: dateTime
		formatString: General Date
		lineageTag: 74a1159c-9bcc-465c-b4f4-25c983a12fb9
		summarizeBy: none
		sourceColumn: DT_ENTRADA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_PESSOA_FISICA
		dataType: string
		lineageTag: ff73eb1a-8209-41cd-8e2a-a90611747505
		summarizeBy: none
		sourceColumn: NM_PESSOA_FISICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_NASCIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 75db5dd2-45e8-4261-b6c3-d79e8503c7f0
		summarizeBy: none
		sourceColumn: DT_NASCIMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_PRONTUARIO
		dataType: string
		lineageTag: 4db61f52-cc38-482a-9daf-9ec598d1c487
		summarizeBy: none
		sourceColumn: NR_PRONTUARIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_STATUS_UNIDADE
		dataType: string
		lineageTag: 8bc258e7-bc53-478c-b9da-41229a7bd09e
		summarizeBy: none
		sourceColumn: IE_STATUS_UNIDADE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_SEXO
		dataType: string
		lineageTag: f7c4b67a-e64f-4fcb-8a5e-a322061ac26e
		summarizeBy: none
		sourceColumn: IE_SEXO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_CONVENIO
		dataType: string
		lineageTag: 556520a8-0e73-4469-a83f-e60cfaa6f1d8
		summarizeBy: none
		sourceColumn: DS_CONVENIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_CATEGORIA
		dataType: string
		lineageTag: 6dc2d08b-0c61-4081-a3e1-919e198e6683
		summarizeBy: none
		sourceColumn: DS_CATEGORIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_PACIENTE_RESERVA
		dataType: string
		lineageTag: bf1c10ff-b97c-4611-b94c-a49caf1e60f3
		summarizeBy: none
		sourceColumn: CD_PACIENTE_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_PACIENTE_RESERVA
		dataType: string
		lineageTag: 13e148b2-0097-415b-9542-e888f55eeede
		summarizeBy: none
		sourceColumn: NM_PACIENTE_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_CONVENIO_RESERVA
		dataType: string
		lineageTag: 12aad564-7e17-451f-bfe8-b9d709a6ff57
		summarizeBy: none
		sourceColumn: CD_CONVENIO_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_USUARIO_RESERVA
		dataType: string
		lineageTag: 8b96ec41-538e-4ff1-aba7-8bf7aad21710
		summarizeBy: none
		sourceColumn: NM_USUARIO_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_CRM
		dataType: string
		lineageTag: d5e2fa55-1278-4636-95b0-6b33af1075c6
		summarizeBy: none
		sourceColumn: NR_CRM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_GUERRA
		dataType: string
		lineageTag: e6f0251d-927b-4144-9dbf-02e3c984fe0e
		summarizeBy: none
		sourceColumn: NM_GUERRA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_CLASSE_ACOMODACAO
		dataType: string
		lineageTag: 1e3baec3-3854-47dd-bc99-887250701f6e
		summarizeBy: none
		sourceColumn: IE_CLASSE_ACOMODACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_SEXO_PACIENTE
		dataType: string
		lineageTag: 393334d3-ad95-42d8-9b72-3a82f126fb9a
		summarizeBy: none
		sourceColumn: IE_SEXO_PACIENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_SEXO_FIXO
		dataType: string
		lineageTag: 5efd2aeb-13e6-46cd-9c5f-e804d574199b
		summarizeBy: none
		sourceColumn: IE_SEXO_FIXO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_STATUS_UNIDADE
		dataType: string
		lineageTag: 425a24d6-5143-41d1-9ae9-174d0e6df70d
		summarizeBy: none
		sourceColumn: DS_STATUS_UNIDADE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_OBSERVACAO
		dataType: string
		lineageTag: c2bbaed5-bb16-4df4-a582-eeec5989ed9b
		summarizeBy: none
		sourceColumn: DS_OBSERVACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QT_DIA_PERMANENCIA
		dataType: double
		lineageTag: e8534319-9705-4990-adce-22dfe7acea25
		summarizeBy: sum
		sourceColumn: QT_DIA_PERMANENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DT_INICIO_HIGIENIZACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: d048c41f-8a27-4313-8f7b-1dcaa2edac23
		summarizeBy: none
		sourceColumn: DT_INICIO_HIGIENIZACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_HIGIENIZACAO
		dataType: dateTime
		formatString: General Date
		lineageTag: acf5975f-6ed6-43a4-8a87-9e6b2670a114
		summarizeBy: none
		sourceColumn: DT_HIGIENIZACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_INTERNO
		dataType: int64
		formatString: 0
		lineageTag: de9641b8-da29-4115-9f64-28e04b8a16f7
		summarizeBy: sum
		sourceColumn: NR_SEQ_INTERNO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_PREVISTO_ALTA
		dataType: dateTime
		formatString: General Date
		lineageTag: 2a4a0010-3528-4a1e-ac99-7bcac40921e2
		summarizeBy: none
		sourceColumn: DT_PREVISTO_ALTA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_ALTA_MEDICO
		dataType: dateTime
		formatString: General Date
		lineageTag: 6adbcbf8-9eac-455b-8931-5616d8b20fd7
		summarizeBy: none
		sourceColumn: DT_ALTA_MEDICO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_USUARIO_HIGIENIZACAO
		dataType: string
		lineageTag: db25f87f-7f2b-45d0-890b-1a068eb84826
		summarizeBy: none
		sourceColumn: NM_USUARIO_HIGIENIZACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NM_USUARIO_FIM_HIGIENIZACAO
		dataType: string
		lineageTag: 1c9639d6-acc9-4a09-8c3a-23d51eb80222
		summarizeBy: none
		sourceColumn: NM_USUARIO_FIM_HIGIENIZACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_RAMAL
		dataType: string
		lineageTag: fb988ab5-d480-4694-b847-ab8ee4407783
		summarizeBy: none
		sourceColumn: NR_RAMAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_TEMPORARIO
		dataType: string
		lineageTag: e3141c38-c25e-417a-948d-b80eae86eb3e
		summarizeBy: none
		sourceColumn: IE_TEMPORARIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_TIPO_RESERVA
		dataType: string
		lineageTag: dd09aefe-11c4-49b4-b6ed-c11b91f21693
		summarizeBy: none
		sourceColumn: IE_TIPO_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_TIPO_ACOMODACAO
		dataType: string
		lineageTag: f83e17e5-30f3-46f8-81ed-9f7769061a22
		summarizeBy: none
		sourceColumn: CD_TIPO_ACOMODACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_PROBABILIDADE_ALTA
		dataType: string
		lineageTag: 328b890b-197f-46f2-8c4f-4b4fb420ee92
		summarizeBy: none
		sourceColumn: IE_PROBABILIDADE_ALTA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_PROBABILIDADE
		dataType: string
		lineageTag: a2caf6ec-c976-4452-90a4-5085e8344d54
		summarizeBy: none
		sourceColumn: DS_PROBABILIDADE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_PSICOLOGO
		dataType: string
		lineageTag: 48f83b97-1457-4207-89c6-d990edf9e348
		summarizeBy: none
		sourceColumn: CD_PSICOLOGO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DS_OCUPACAO
		dataType: string
		lineageTag: f09fec4f-ebc7-486d-8b4c-bcb8c6e7da5b
		summarizeBy: none
		sourceColumn: DS_OCUPACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_AGRUPAMENTO
		dataType: int64
		formatString: 0
		lineageTag: 025eb36e-9b58-444e-8102-24dd3f61a196
		summarizeBy: sum
		sourceColumn: NR_AGRUPAMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QT_PESO_MAXIMO
		dataType: double
		lineageTag: 8394986b-32c6-4f2a-a1b1-89c3ab7fae34
		summarizeBy: sum
		sourceColumn: QT_PESO_MAXIMO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QT_ALTURA_MAXIMA
		dataType: double
		lineageTag: c6733308-41b7-43d2-b1a3-93e5867f509c
		summarizeBy: sum
		sourceColumn: QT_ALTURA_MAXIMA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CD_CONVENIO
		dataType: string
		lineageTag: 9bfae4fa-b22f-4082-9c51-7498a44d4010
		summarizeBy: none
		sourceColumn: CD_CONVENIO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QT_TEMPO_PREV_HIGIEN
		dataType: double
		lineageTag: fdb10bcd-1338-48fc-af1f-93f3200844e7
		summarizeBy: sum
		sourceColumn: QT_TEMPO_PREV_HIGIEN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NR_SEQ_MOTIVO_RESERVA
		dataType: int64
		formatString: 0
		lineageTag: 8a3af219-9c3b-4ccc-8b3b-4a9a656f7938
		summarizeBy: sum
		sourceColumn: NR_SEQ_MOTIVO_RESERVA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_ACOMPANHANTE
		dataType: string
		lineageTag: 532ca4eb-528e-44b7-8dc3-cf04f47dd008
		summarizeBy: none
		sourceColumn: IE_ACOMPANHANTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_APRESENT
		dataType: int64
		formatString: 0
		lineageTag: b2dccb7c-39dd-4697-bcde-a4aee31d3a54
		summarizeBy: sum
		sourceColumn: NR_SEQ_APRESENT

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_RADIOTERAPIA
		dataType: string
		lineageTag: 005f7b8d-4499-4f90-99f2-21b46ac174f7
		summarizeBy: none
		sourceColumn: IE_RADIOTERAPIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_ATEND_ALTA
		dataType: int64
		formatString: 0
		lineageTag: 6e028e70-27cb-4b4d-bc88-1b82f20a1f73
		summarizeBy: sum
		sourceColumn: NR_ATEND_ALTA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_INTERDITADO_RADIACAO
		dataType: string
		lineageTag: f6142ee7-8669-4429-9f5d-1118790db6f3
		summarizeBy: none
		sourceColumn: IE_INTERDITADO_RADIACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_PERFIL
		dataType: int64
		formatString: 0
		lineageTag: 697fb343-1e79-474f-a620-44e2c8625498
		summarizeBy: sum
		sourceColumn: NR_SEQ_PERFIL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_MOTIVO_ALTA_MEDICA
		dataType: string
		lineageTag: c1d82936-b1cc-4482-ac5f-becae31e23d1
		summarizeBy: none
		sourceColumn: CD_MOTIVO_ALTA_MEDICA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_MEDICO_RESP
		dataType: string
		lineageTag: 134c186c-1f61-47a4-80e1-9eab3ff1e1c5
		summarizeBy: none
		sourceColumn: CD_MEDICO_RESP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_CARATER_INTER_SUS
		dataType: string
		lineageTag: 646f7d48-9f14-4f4b-9dd9-53b875fc13ef
		summarizeBy: none
		sourceColumn: IE_CARATER_INTER_SUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CD_MEDICO_REFERIDO
		dataType: string
		lineageTag: 0b6d0f31-8d2d-422e-b820-7df831a076d2
		summarizeBy: none
		sourceColumn: CD_MEDICO_REFERIDO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_LOCAL_PA
		dataType: int64
		formatString: 0
		lineageTag: bbb09f06-4dc2-45f3-bad3-7869d16e610d
		summarizeBy: sum
		sourceColumn: NR_SEQ_LOCAL_PA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_PACIENTE_ISOLADO
		dataType: string
		lineageTag: 8cade845-4669-4318-95d3-bf5379591295
		summarizeBy: none
		sourceColumn: IE_PACIENTE_ISOLADO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column NR_SEQ_ATEPACU
		dataType: int64
		formatString: 0
		lineageTag: d43d8e93-7794-4fe5-bb71-de76cbba4038
		summarizeBy: sum
		sourceColumn: NR_SEQ_ATEPACU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column IE_ORDEM
		dataType: int64
		formatString: 0
		lineageTag: 4f99b635-226d-4eaa-bbde-3f0e78f31827
		summarizeBy: sum
		sourceColumn: IE_ORDEM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MEDIA_QT_DIA_PERMANENCIA_SETOR_CID
		dataType: double
		lineageTag: e700f2ca-5c9b-4c99-a6c3-9e384add8ac3
		summarizeBy: count
		sourceColumn: MEDIA_QT_DIA_PERMANENCIA_SETOR_CID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEDIANA_QT_DIA_PERMANENCIA_SETOR_CID
		dataType: double
		lineageTag: d9d9116b-869b-42bc-a67d-2f082d23f490
		summarizeBy: count
		sourceColumn: MEDIANA_QT_DIA_PERMANENCIA_SETOR_CID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QT_REGISTROS_SETOR_CID
		dataType: int64
		formatString: 0
		lineageTag: d4d0aa09-99a5-488e-a8da-14ddd505a523
		summarizeBy: count
		sourceColumn: QT_REGISTROS_SETOR_CID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dt_carga
		dataType: dateTime
		formatString: Long Date
		lineageTag: f6d57ae6-0bdb-4bd6-a6f5-c4e632772efb
		summarizeBy: none
		sourceColumn: dt_carga

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Indicador 06' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("192.168.6.2:5432", "prohmdw"),
				    #"Exportar Planilha" = Fonte{[Schema="public", Item="fato_desospitalizacao_permanencia_cid_setor"]}[Data],
				    #"Cabeçalhos Promovidos" = #"Exportar Planilha",
				
				    ColunasExistentes = Table.ColumnNames(#"Cabeçalhos Promovidos"),
				
				    ConverterParaDateTime = (v as any) as nullable datetime =>
				        let
				            Resultado =
				                if v = null then
				                    null
				                else if Value.Is(v, type datetime) then
				                    v
				                else if Value.Is(v, type date) then
				                    DateTime.From(v)
				                else if Value.Is(v, type number) then
				                    try DateTime.From(v) otherwise null
				                else
				                    let
				                        Texto = Text.Trim(Text.From(v)),
				
				                        TentativaNumeroPT = try Number.FromText(Texto, "pt-BR"),
				                        TentativaNumeroUS = try Number.FromText(Texto, "en-US"),
				
				                        TentativaDataHoraBR = try DateTime.FromText(Texto, [Culture = "pt-BR"]),
				                        TentativaDataHoraUS = try DateTime.FromText(Texto, [Culture = "en-US"]),
				
				                        TentativaDataBR = try Date.FromText(Texto, [Culture = "pt-BR"]),
				                        TentativaDataUS = try Date.FromText(Texto, [Culture = "en-US"])
				                    in
				                        if Texto = "" then
				                            null
				                        else if not TentativaNumeroPT[HasError] then
				                            try DateTime.From(TentativaNumeroPT[Value]) otherwise null
				                        else if not TentativaNumeroUS[HasError] then
				                            try DateTime.From(TentativaNumeroUS[Value]) otherwise null
				                        else if not TentativaDataHoraBR[HasError] then
				                            TentativaDataHoraBR[Value]
				                        else if not TentativaDataHoraUS[HasError] then
				                            TentativaDataHoraUS[Value]
				                        else if not TentativaDataBR[HasError] then
				                            DateTime.From(TentativaDataBR[Value])
				                        else if not TentativaDataUS[HasError] then
				                            DateTime.From(TentativaDataUS[Value])
				                        else
				                            null
				        in
				            Resultado,
				
				    ColunasDataHora = {
				        "DT_ENTRADA_UNIDADE",
				        "DT_ENTRADA",
				        "DT_NASCIMENTO",
				        "DT_INICIO_HIGIENIZACAO",
				        "DT_HIGIENIZACAO",
				        "DT_PREVISTO_ALTA",
				        "DT_ALTA_MEDICO"
				    },
				
				    ColunasDataHoraExistentes = List.Intersect({ColunasDataHora, ColunasExistentes}),
				
				    #"Datas Ajustadas" = Table.TransformColumns(
				        #"Cabeçalhos Promovidos",
				        List.Transform(
				            ColunasDataHoraExistentes,
				            (col) => {col, each ConverterParaDateTime(_), type nullable datetime}
				        )
				    ),
				
				    TiposDesejados = {
				        {"NR_ATENDIMENTO", Int64.Type},
				        {"DT_ENTRADA_UNIDADE", type datetime},
				        {"CD_UNIDADE", type text},
				        {"CD_UNIDADE_BASICA", type text},
				        {"CD_UNIDADE_COMPL", type text},
				        {"DT_ENTRADA", type datetime},
				        {"NM_PESSOA_FISICA", type text},
				        {"CD_SETOR_ATENDIMENTO", Int64.Type},
				        {"CD_PESSOA_FISICA", type text},
				        {"DT_NASCIMENTO", type datetime},
				        {"NR_PRONTUARIO", type text},
				        {"IE_STATUS_UNIDADE", type text},
				        {"IE_SEXO", type text},
				        {"DS_CONVENIO", type text},
				        {"DS_CATEGORIA", type text},
				        {"CD_PACIENTE_RESERVA", type text},
				        {"NM_PACIENTE_RESERVA", type text},
				        {"CD_CONVENIO_RESERVA", type text},
				        {"NM_USUARIO_RESERVA", type text},
				        {"NR_CRM", type text},
				        {"NM_GUERRA", type text},
				        {"IE_CLASSE_ACOMODACAO", type text},
				        {"IE_SEXO_PACIENTE", type text},
				        {"IE_SEXO_FIXO", type text},
				        {"DS_STATUS_UNIDADE", type text},
				        {"DS_OBSERVACAO", type text},
				        {"QT_DIA_PERMANENCIA", type number},
				        {"DT_INICIO_HIGIENIZACAO", type datetime},
				        {"DT_HIGIENIZACAO", type datetime},
				        {"NR_SEQ_INTERNO", Int64.Type},
				        {"DT_PREVISTO_ALTA", type datetime},
				        {"DT_ALTA_MEDICO", type datetime},
				        {"NM_USUARIO_HIGIENIZACAO", type text},
				        {"NM_USUARIO_FIM_HIGIENIZACAO", type text},
				        {"NR_RAMAL", type text},
				        {"IE_TEMPORARIO", type text},
				        {"IE_TIPO_RESERVA", type text},
				        {"CD_TIPO_ACOMODACAO", type text},
				        {"IE_PROBABILIDADE_ALTA", type text},
				        {"DS_PROBABILIDADE", type text},
				        {"CD_PSICOLOGO", type text},
				        {"DS_OCUPACAO", type text},
				        {"NR_AGRUPAMENTO", Int64.Type},
				        {"QT_PESO_MAXIMO", type number},
				        {"QT_ALTURA_MAXIMA", type number},
				        {"CD_CONVENIO", type text},
				        {"QT_TEMPO_PREV_HIGIEN", type number},
				        {"NR_SEQ_MOTIVO_RESERVA", Int64.Type},
				        {"IE_ACOMPANHANTE", type text},
				        {"NR_SEQ_APRESENT", Int64.Type},
				        {"IE_RADIOTERAPIA", type text},
				        {"NR_ATEND_ALTA", Int64.Type},
				        {"IE_INTERDITADO_RADIACAO", type text},
				        {"CD_ESTABELECIMENTO", type text},
				        {"NR_SEQ_PERFIL", Int64.Type},
				        {"CD_MOTIVO_ALTA_MEDICA", type text},
				        {"CD_MEDICO_RESP", type text},
				        {"IE_CARATER_INTER_SUS", type text},
				        {"CD_MEDICO_REFERIDO", type text},
				        {"NR_SEQ_LOCAL_PA", Int64.Type},
				        {"IE_PACIENTE_ISOLADO", type text},
				        {"NR_SEQ_ATEPACU", Int64.Type},
				        {"IE_ORDEM", Int64.Type},
				        {"CD_CID", type text},
				        {"MEDIA_QT_DIA_PERMANENCIA_SETOR_CID", type number},
				        {"MEDIANA_QT_DIA_PERMANENCIA_SETOR_CID", type number},
				        {"QT_REGISTROS_SETOR_CID", Int64.Type}
				    },
				
				    TiposParaAplicar = List.Select(
				        TiposDesejados,
				        each List.Contains(ColunasExistentes, _{0})
				    ),
				
				    #"Tipos Alterados" = Table.TransformColumnTypes(
				        #"Datas Ajustadas",
				        TiposParaAplicar
				    )
				
				in
				    #"Tipos Alterados"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

