table 'Indicador 13'
	lineageTag: 3475e4bd-46bb-4918-899f-714be8fce3ee

	column NR_ATENDIMENTO
		dataType: int64
		lineageTag: aa339c9b-1be8-44e9-8355-c458c846d424
		summarizeBy: sum
		sourceColumn: NR_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column CD_PACIENTE
		dataType: string
		lineageTag: e5b1dee4-f373-41cd-a919-482b6a7146fa
		summarizeBy: none
		sourceColumn: CD_PACIENTE

		annotation SummarizationSetBy = Automatic

	column PACIENTE
		dataType: string
		lineageTag: f9a2d409-5fe1-45dc-baf1-d9abb2d453ac
		summarizeBy: none
		sourceColumn: PACIENTE

		annotation SummarizationSetBy = Automatic

	column DT_ENTRADA
		dataType: dateTime
		lineageTag: 130827cc-5959-46ec-ae1e-f0b106280a42
		summarizeBy: none
		sourceColumn: DT_ENTRADA

		annotation SummarizationSetBy = Automatic

	column DT_ALTA
		dataType: dateTime
		lineageTag: 3ef2f645-103e-47b7-ac85-22dc91aa868a
		summarizeBy: none
		sourceColumn: DT_ALTA

		annotation SummarizationSetBy = Automatic

	column DT_SAIDA_REAL
		dataType: dateTime
		lineageTag: f2d10a56-8364-474f-b00a-3f25e721db3e
		summarizeBy: none
		sourceColumn: DT_SAIDA_REAL

		annotation SummarizationSetBy = Automatic

	column DT_PREVISTA_ALTA
		dataType: dateTime
		lineageTag: 5dd8a0f7-952a-4b05-abd9-68c74844c4c0
		summarizeBy: none
		sourceColumn: DT_PREVISTA_ALTA

		annotation SummarizationSetBy = Automatic

	column DT_EVENTO_PREVISAO
		dataType: dateTime
		lineageTag: dd779813-3519-42f0-8bc2-c59b25e29792
		summarizeBy: none
		sourceColumn: DT_EVENTO_PREVISAO

		annotation SummarizationSetBy = Automatic

	column DT_ALTA_REAL
		dataType: dateTime
		lineageTag: 42858fdb-e054-44bf-9b19-51ab6dbff9bb
		summarizeBy: none
		sourceColumn: DT_ALTA_REAL

		annotation SummarizationSetBy = Automatic

	column QT_DIF_DIAS_PREVISTO_REAL
		dataType: double
		lineageTag: 5878ed00-01a8-47bd-873c-a870ba40e750
		summarizeBy: sum
		sourceColumn: QT_DIF_DIAS_PREVISTO_REAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FL_ACERTO_EXATO
		dataType: string
		lineageTag: fd6bcc8c-31f9-4641-84a8-06d9d540da2d
		summarizeBy: none
		sourceColumn: FL_ACERTO_EXATO

		annotation SummarizationSetBy = Automatic

	column FL_ACERTO_TOLERANCIA
		dataType: string
		lineageTag: c9a9a5c8-9084-4dd9-b80b-78b7fa23da4c
		summarizeBy: none
		sourceColumn: FL_ACERTO_TOLERANCIA

		annotation SummarizationSetBy = Automatic

	column INDICADOR_PERCENTUAL_ACURACIA
		dataType: double
		lineageTag: 2449a549-b2cc-4a93-93c3-659abd07e931
		summarizeBy: sum
		sourceColumn: INDICADOR_PERCENTUAL_ACURACIA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CD_MEDICO
		dataType: string
		lineageTag: 44b38af6-4bac-4263-90e4-978bc71cc896
		summarizeBy: none
		sourceColumn: CD_MEDICO

		annotation SummarizationSetBy = Automatic

	column CD_SETOR
		dataType: int64
		formatString: 0
		lineageTag: 15ed1795-d590-4007-b368-96d6c9d7a6d4
		summarizeBy: none
		sourceColumn: CD_SETOR

		annotation SummarizationSetBy = Automatic

	column dt_carga
		dataType: dateTime
		formatString: Long Date
		lineageTag: 377f6e39-1d50-4733-9093-5dd022a6cb4a
		summarizeBy: none
		sourceColumn: dt_carga

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Indicador 13' = m
		mode: import
		source =
				let
				    Fonte = PostgreSQL.Database("192.168.6.2:5432", "prohmdw"),
				    Planilha = Fonte{[Schema="public", Item="fato_desospitalizacao_acuracia_alta"]}[Data],
				    Headers = Planilha,
				
				    ColunasExistentes = Table.ColumnNames(Headers),
				
				    ConverterParaDateTime = (v as any) as nullable datetime =>
				        let
				            Resultado =
				                if v = null then
				                    null
				                else if Value.Is(v, type datetime) then
				                    v
				                else if Value.Is(v, type date) then
				                    DateTime.From(v)
				                else if Value.Is(v, type number) then
				                    try DateTime.From(v) otherwise null
				                else
				                    let
				                        Texto = Text.Trim(Text.From(v)),
				
				                        TentativaNumeroPT = try Number.FromText(Texto, "pt-BR"),
				                        TentativaNumeroUS = try Number.FromText(Texto, "en-US"),
				
				                        TentativaDataHoraBR = try DateTime.FromText(Texto, [Culture = "pt-BR"]),
				                        TentativaDataHoraUS = try DateTime.FromText(Texto, [Culture = "en-US"]),
				
				                        TentativaDataBR = try Date.FromText(Texto, [Culture = "pt-BR"]),
				                        TentativaDataUS = try Date.FromText(Texto, [Culture = "en-US"])
				                    in
				                        if Texto = "" then
				                            null
				                        else if not TentativaNumeroPT[HasError] then
				                            try DateTime.From(TentativaNumeroPT[Value]) otherwise null
				                        else if not TentativaNumeroUS[HasError] then
				                            try DateTime.From(TentativaNumeroUS[Value]) otherwise null
				                        else if not TentativaDataHoraBR[HasError] then
				                            TentativaDataHoraBR[Value]
				                        else if not TentativaDataHoraUS[HasError] then
				                            TentativaDataHoraUS[Value]
				                        else if not TentativaDataBR[HasError] then
				                            DateTime.From(TentativaDataBR[Value])
				                        else if not TentativaDataUS[HasError] then
				                            DateTime.From(TentativaDataUS[Value])
				                        else
				                            null
				        in
				            Resultado,
				
				    ColunasDataHora = {
				        "DT_ENTRADA",
				        "DT_ALTA",
				        "DT_SAIDA_REAL",
				        "DT_PREVISTA_ALTA",
				        "DT_EVENTO_PREVISAO",
				        "DT_ALTA_REAL"
				    },
				
				    ColunasDataHoraExistentes = List.Intersect({ColunasDataHora, ColunasExistentes}),
				
				    DatasAjustadas = Table.TransformColumns(
				        Headers,
				        List.Transform(
				            ColunasDataHoraExistentes,
				            (col) => {col, each ConverterParaDateTime(_), type nullable datetime}
				        )
				    ),
				
				    TiposDesejados = {
				        {"NR_ATENDIMENTO", Int64.Type},
				        {"CD_PACIENTE", type text},
				        {"CD_MEDICO", type text},
				        {"CD_SETOR", Int64.Type},
				        {"PACIENTE", type text},
				        {"DT_ENTRADA", type datetime},
				        {"DT_ALTA", type datetime},
				        {"DT_SAIDA_REAL", type datetime},
				        {"DT_PREVISTA_ALTA", type datetime},
				        {"DT_EVENTO_PREVISAO", type datetime},
				        {"DT_ALTA_REAL", type datetime},
				        {"QT_DIF_DIAS_PREVISTO_REAL", type number},
				        {"FL_ACERTO_EXATO", type text},
				        {"FL_ACERTO_TOLERANCIA", type text},
				        {"INDICADOR_PERCENTUAL_ACURACIA", type number}
				    },
				
				    TiposParaAplicar = List.Select(
				        TiposDesejados,
				        each List.Contains(ColunasExistentes, _{0})
				    ),
				
				    Tipos = Table.TransformColumnTypes(
				        DatasAjustadas,
				        TiposParaAplicar
				    )
				in
				    Tipos

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

